### ISSUE TITLE
No support for PDF layout options in 2.0.0?

### ISSUE THREAD

**Issue by tarvainen** [by-pinja/pdf-storage#28]
I see that the `options` section exists in the default request in the API docs but it also looks like at https://github.com/protacon/pdf-storage/blob/master/Pdf/PdfConvert.cs#L23 `options` parameter is not used at all. 

Quick googeling told me that it's not even possible to parametrise Chrome's PDF generation from command line in the way with PhantomJS (like orientation or page size)? Is this right or am I just missing something?

[Release notes](https://github.com/protacon/pdf-storage/releases/tag/2.0.0) tells me that PDF options has been **changed** but this was not expected. 🙈

**Comment by savpek** [comment]
Some of them can be replaced with chrome debugger api, what options were used?

**Comment by savpek** [comment]
Implemented at https://github.com/by-pinja/pdf-storage/pull/60
